// Verdict コメントの本文組み立てと入力検証
//
// 固定部分は Mcp-Docker の「Verdict 照合規則」と一字一句一致させる。reviewed 側
// （review-raven-thread-owl-cycle）はこの 3 行を正規表現で照合してマージゲートを
// 通すため、書式の揺れがそのままサイクル停止（VERDICT_FORMAT_MISMATCH）になる。
// プロンプト指示では防げなかったので、組み立てをサーバー側へ寄せている。

const VERDICT_HEADING = "## @thread-owl Review Verdict: APPROVED";
const VERDICT_STATUS_LINE = "- Status: `READY_TO_MERGE`";

/** 照合規則が「各行ちょうど 1 行」を要求するため、summary 側に現れてはならない行。 */
const RESERVED_LINE_PATTERNS = [
  /^## @thread-owl Review Verdict: APPROVED$/,
  /^- Reviewed HEAD SHA: `[0-9a-f]{40}`$/,
  /^- Status: `READY_TO_MERGE`$/,
] as const;

/** 照合規則が Verdict 候補を選ぶ目印。summary に混ぜると候補の特定が壊れる。 */
const VERDICT_MARKER = "Review Verdict";

const FULL_SHA = /^[0-9a-f]{40}$/;

export class InvalidVerdictInputError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "InvalidVerdictInputError";
  }
}

export function assertFullCommitSha(headSha: string): void {
  if (!FULL_SHA.test(headSha)) {
    throw new InvalidVerdictInputError(
      "headSha must be a full 40-character lowercase hex commit SHA",
    );
  }
}

export function assertVerdictSummary(summary: string): void {
  if (summary.includes(VERDICT_MARKER)) {
    throw new InvalidVerdictInputError(
      `summary must not contain "${VERDICT_MARKER}"; the heading is generated by this tool`,
    );
  }
  for (const line of splitLines(summary)) {
    if (RESERVED_LINE_PATTERNS.some((pattern) => pattern.test(line))) {
      throw new InvalidVerdictInputError(
        "summary must not contain a Verdict heading, HEAD SHA line, or Status line; they are generated by this tool",
      );
    }
  }
}

/** 照合規則と同じ行分割（`\n` で分割し、各行末尾の `\r` を 1 個だけ除去する）。 */
function splitLines(body: string): string[] {
  return body.split("\n").map((line) => (line.endsWith("\r") ? line.slice(0, -1) : line));
}

export function buildVerdictBody(summary: string, headSha: string): string {
  return [
    VERDICT_HEADING,
    "",
    summary.trim(),
    "",
    "---",
    `- Reviewed HEAD SHA: \`${headSha}\``,
    VERDICT_STATUS_LINE,
  ].join("\n");
}
